name: 'Rasa NLU Target Files'
description: 'A GitHub action to put Rasa NLU data in prescribed target files'
inputs:
  target_files_config:
    description: YAML file containing NLU target files config. 
    required: false
    default: target_files_config.yml

branding:
  icon: 'message-square'  
  color: 'blue'

runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install -r "${{ github.action_path }}"/requirements.txt
      shell: bash
    - name: Run Result Comparison
      shell: bash
      run: |
        export PYTHONPATH=$PYTHONPATH:${{ github.action_path }}
        python -m nlu_target_files enforce --target_files_config ${{ inputs.target_files_config }}
