name: 'Rasa NLU Target Files'
description: 'A GitHub action to put Rasa NLU data in prescribed target files'
inputs:
  target_files_config:
    description: YAML file containing NLU target files config. 
    required: false
    default: target_files.yml

branding:
  icon: 'message-square'  
  color: 'blue'

runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install -r "${{ github.action_path }}"/requirements.txt
      shell: bash
    - name: Set boolean options
      id: bool_opts
      run: |
        case "$(tr "[:upper:]" "[:lower:]" <<< "${{ inputs.update_config_file }}")" in
            "true") echo "::set-output name=update_config_file::--update_config_file" ;;
            *) echo "::set-output name=update_config_file::";;
        esac

      shell: bash
    - name: Run Result Comparison
      shell: bash
      run: |
        export PYTHONPATH=$PYTHONPATH:${{ github.action_path }}
        python -m nlu_target_files enforce \
          --target_files_config ${{ inputs.target_files_config }} \
          {{ steps.bool_opts.outputs.update_config_file }}
